# Site settings
title: Jason Blog
SEOTitle: Jason Blog
header-img: img/home-bg.jpg
email: songjisong@foxmail.com
description: "description"
keyword: "keyword"
url: "https://jasonsonghoho.github.io/gitpage/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'
