# Site settings
title: Jason Blog
SEOTitle: Jason Blog
header-img: img/home-bg.jpg
email:
 fox: songjisong@foxmail.com
 gmail: songjisong93@gmail.com
description: "Jason Blog"
keyword: "Jason Blog"
url: "http://jasonsonghoho.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

markdown: kramdown

logo: "/css/2017_style/img/logos/favicon.ico"

imgurl:
 tec: "http://jasonsonghoho.github.io/blog_images/technology"
 life: "http://jasonsonghoho.github.io/blog_images/life"

social:
  name: My Facebook Page
  link: "http://www.facebook.com/jisong.song.12"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://www.facebook.com/jisong.song.12
  - title: weibo
    url: http://weibo.com/u/3278732140
  - title: github
    url: http://github.com/JasonSongHoho

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag